name: 🚀 Build & Publish Python Package

on:
  workflow_call:
    inputs:
      source_branch:
        description: "Source branch to be checked out from"
        required: false
        type: string
        default: "main"
      pypi_repository:
        description: "Name of the package to be built and deployed"
        required: false
        type: string
        default: testpypi
      version_update:
        description: "Semantic version update (patch, minor or major):"
        required: true
        type: string
        default: patch

  workflow_dispatch:
    inputs:
      source_repo:
        description: "Source repository to be checked out from"
        required: true
        type: string
        default: "usepolvo/usepolvo-python"
      source_branch:
        description: "Source branch to be checked out from"
        required: true
        type: string
        default: "main"
      pypi_repository:
        description: "Name of the package to be built and deployed"
        required: true
        type: string
        default: testpypi
      version_update:
        description: "Semantic version update (patch, minor or major):"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-publish-package:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN || secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.source_repo || github.repository }}
          ref: ${{ inputs.source_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install build-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt

      - name: Bump up package version
        run: |
          bump2version ${{ inputs.version_update }}

      - name: Commit and push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "chore: version update"
          git push

      - name: Build package and publish
        working-directory: src
        run: |
          python -m build
          python -m twine upload \
          --repository ${{ inputs.pypi_repository }} \
          --username '__token__' \
          --password '${{ secrets.TEST_PYPI_TOKEN }}' \
          dist/* \
          --verbose
